### ISSUE TITLE
Detected problem at exit_write_lock

### ISSUE THREAD

**Issue by alcubo01** [duvni/ReaderWriterLock_Python#1]
I detected a blocking situation at **downgrade_write_to_read_lock**. The problem raises when calling to **exit_write_lock**:

```
 with self._sync_lock:
    if self.is_write_lock_held:
        self._writing_thread = 0
        self._write_lock.release()

    #This code is inside the "with", so self._sync_lock is locked and  
    #enter_read_lock() will try to lock it again
     if downgrade_to_read and not self.is_read_lock_held:
         self.enter_read_lock()  
```

To solve the problem, i just put the enter_read_lock code out of the with clause:

 ```
with self._sync_lock:
      if self.is_write_lock_held:
          self._writing_thread = 0
          self._write_lock.release()

if downgrade_to_read and not self.is_read_lock_held:
           self.acquire_read()
```

**Comment by duvni** [comment]
Since _sync_lock is RLock it means that the owning thread can re-lock it as many times as it wants, but has to unlock it the same number of times.

So in this situation the thread will lock _sync_lock twice, once in exit_write_lock and once in enter_read_lock without hanging.

You can test it in test_upgrade_read_to_write_lock unit test (that also does the downgrading).

Here's the documentation for RLock:
https://docs.python.org/2.4/lib/rlock-objects.html

Note that your solution of taking enter_read_lock outside the _sync_lock raises a situation where another thread can acquire the write lock **before** this thread acquires the read lock, hence downgrading to read lock is not an atomic operation anymore and has to wait for that other thread to finish writing (which is not the expected behavior).
